FROM kishlin/base-kishlin-node:8.16-alpine

VOLUME /srv/cache

RUN apk add --no-cache build-base \
        bash \
        libpng-dev \
        pngquant \
        gcc \
        wget \
        git \
        zip \
